services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=bishamba_tips_db'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5433:5432'
    volumes:
      - bishamba_tips_volume:/var/lib/postgresql/data

volumes:
  bishamba_tips_volume: